"""enforce one membership per user

Revision ID: 7711ffe573bc
Revises: 7d2d9d1e6649
Create Date: 2026-09-14 17:11:47.160263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7711ffe573bc'
down_revision: Union[str, Sequence[str], None] = '7d2d9d1e6649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_memberships_user_id', 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_memberships_user_id', 'users', type_='unique')
    # ### end Alembic commands ###
